.

diff --git a/script-v6/Otros/ejecutar/msg b/script-v6/Otros/ejecutar/msg
--- a/script-v6/Otros/ejecutar/msg
+++ b/script-v6/Otros/ejecutar/msg
@@ -34,44 +34,27 @@ shutdown() {
     exit 0
 }
 
-
 selection_fun() {
-    local selection=""
+    local selection="null"
+    local opc=$1
     local range
+    for((i=0; i<=${opc}; i++)); do range[$i]="$i "; done
     local error_count=0
-    local max_errors=5  
-
-    
-    for ((i=0; i<=$1; i++)); do range[$i]="$i"; done
-    
-    while true; do
-        
-        if [[ $error_count -lt $max_errors ]]; then
-            echo -ne "\033[1;37m ► Opcion : " >&2
-        fi
-        
-       
-        read -r selection 2>/dev/null
+    while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
+        echo -ne "\033[1;37m ► Opcion : " >&2
+        read -r selection 2>/dev/null 
         tput cuu1 >&2 && tput dl1 >&2
-
-        
-        if [[ -z "$selection" ]] || [[ ! " ${range[*]} " =~ " $selection " ]]; then
-            error_count=$((error_count + 1))
-            
-            
-            if [[ $error_count -lt $max_errors ]]; then
-                echo -e "Error: Opción no válida. Errores: $error_count/$max_errors" >&2
-            fi
-            if [[ $error_count -ge $max_errors ]]; then
-                echo "Demasiados errores. Saliendo..."
-                shutdown
-            fi
-        else
-            echo "Has seleccionado la opción: $selection"
-            break  
+        ((error_count++))
+        if [[ $error_count -eq 5 ]]; then
+            echo -e "\nDemasiados errores. Saliendo..."
+            shutdown
         fi
     done
+    echo $selection
 }
+
+
+
 
 
 
